include: package:very_good_analysis/analysis_options.2.4.0.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    one_member_abstracts: false