name: find_me_app

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.0
      min_coverage: 0 # will increase this later
